output "route53_nameservers" { value = aws_route53_zone.main.name_servers }
output "cloudfront_domain" { value = local.cdn_ready ? aws_cloudfront_distribution.frontend[0].domain_name : "not yet created — re-run after bootstrap" }
output "app_url" { value = local.cdn_ready ? "https://${var.app_subdomain}.${var.domain_name}" : "pending — trigger workflow again after bootstrap stores ELB hostname" }
output "cluster_name" { value = module.eks.cluster_name }
output "cluster_endpoint" { value = module.eks.cluster_endpoint }
output "ecr_registry" { value = module.ecr.registry_url }
output "documents_bucket" { value = module.security.documents_bucket_name }
output "rag_queue_url" { value = module.sqs.rag_processing_queue_url }
output "appointment_queue_url" { value = module.sqs.appointment_events_queue_url }
output "user_service_role_arn" { value = module.irsa.user_service_role_arn }
output "appointment_service_role_arn" { value = module.irsa.appointment_service_role_arn }
output "health_service_role_arn" { value = module.irsa.health_service_role_arn }
output "document_service_role_arn" { value = module.irsa.document_service_role_arn }
output "rag_service_role_arn" { value = module.irsa.rag_service_role_arn }
output "rag_worker_role_arn" { value = module.irsa.rag_worker_role_arn }
output "keda_role_arn" { value = module.irsa.keda_role_arn }
